#!/bin/bash
mkdir -p ../../../devel/share/urusstudio/lib_finder > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/lib_finder > /dev/null 2> /dev/null
cp ./lib_finder/*.xml ../../../devel/share/urusstudio/lib_finder > /dev/null 2> /dev/null
cp ./lib_finder/*.xml ../../../output/share/urusstudio/lib_finder > /dev/null 2> /dev/null
zip -j9 ../../../devel/share/urusstudio/lib_finder.zip manifest.xml
exit 0
