#! /bin/sh
mkdir -p ../../../devel/share/urusstudio/images/ThreadSearch > /dev/null 2> /dev/null
mkdir -p ../../../devel/share/urusstudio/images/ThreadSearch/16x16 > /dev/null 2> /dev/null
mkdir -p ../../../devel/share/urusstudio/images/ThreadSearch/22x22 > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/images/ThreadSearch > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/images/ThreadSearch/16x16 > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/images/ThreadSearch/22x22 > /dev/null 2> /dev/null
mkdir -p ../../../devel/share/urusstudio/images/settings > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/images/settings > /dev/null 2> /dev/null
cp ./resources/images/*.png ../../../devel/share/urusstudio/images/ThreadSearch/ > /dev/null 2> /dev/null
cp ./resources/images/16x16/*.png ../../../devel/share/urusstudio/images/ThreadSearch/16x16/ > /dev/null 2> /dev/null
cp ./resources/images/22x22/*.png ../../../devel/share/urusstudio/images/ThreadSearch/22x22/ > /dev/null 2> /dev/null
cp ./resources/images/*.png ../../../output/share/urusstudio/images/ThreadSearch/ > /dev/null 2> /dev/null
cp ./resources/images/16x16/*.png ../../../output/share/urusstudio/images/ThreadSearch/16x16/ > /dev/null 2> /dev/null
cp ./resources/images/22x22/*.png ../../../output/share/urusstudio/images/ThreadSearch/22x22/ > /dev/null 2> /dev/null
cp ./resources/*.png ../../../devel/share/urusstudio/images/settings/ > /dev/null 2> /dev/null
cp ./resources/*.png ../../../output/share/urusstudio/images/settings/ > /dev/null 2> /dev/null
exit 0

