#! /bin/sh
mkdir -p ../../../devel/share/urusstudio/images/settings > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/images/settings > /dev/null 2> /dev/null
cp ./Resources/*.png ../../../devel/share/urusstudio/images/settings/ > /dev/null 2> /dev/null
cp ./Resources/*.png ../../../output/share/urusstudio/images/settings/ > /dev/null 2> /dev/null
exit 0

