usr/bin/urusstudio
usr/bin/cb_console_runner
usr/bin/cb_share_config

usr/lib/urusstudio/plugins/libabbreviations.so
usr/lib/urusstudio/plugins/libAstyle.so
usr/lib/urusstudio/plugins/libautosave.so
usr/lib/urusstudio/plugins/libclasswizard.so
usr/lib/urusstudio/plugins/libcodecompletion.so
usr/lib/urusstudio/plugins/libcompiler.so
usr/lib/urusstudio/plugins/libdebugger.so
usr/lib/urusstudio/plugins/libdefaultmimehandler.so
usr/lib/urusstudio/plugins/liboccurrenceshighlighting.so
usr/lib/urusstudio/plugins/libopenfileslist.so
usr/lib/urusstudio/plugins/libprojectsimporter.so
usr/lib/urusstudio/plugins/libscriptedwizard.so
usr/lib/urusstudio/plugins/libtodo.so
../lintian/codeblocks  usr/share/lintian/overrides

