#! /bin/sh
#

mkdir -p ../../../devel/share/urusstudio/images/DoxyBlocks > /dev/null 2> /dev/null
mkdir -p ../../../devel/share/urusstudio/images/DoxyBlocks/16x16 > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/images/DoxyBlocks > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/images/DoxyBlocks/16x16 > /dev/null 2> /dev/null
mkdir -p ../../../devel/share/urusstudio/images/settings > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/images/settings > /dev/null 2> /dev/null
cp ./images/*.png ../../../devel/share/urusstudio/images/DoxyBlocks/ > /dev/null 2> /dev/null
cp ./images/16x16/*.png ../../../devel/share/urusstudio/images/DoxyBlocks/16x16/ > /dev/null 2> /dev/null
cp ./images/*.png ../../../output/share/urusstudio/images/DoxyBlocks/ > /dev/null 2> /dev/null
cp ./images/16x16/*.png ../../../output/share/urusstudio/images/DoxyBlocks/16x16/ > /dev/null 2> /dev/null
cp ./*.png ../../../devel/share/urusstudio/images/settings/ > /dev/null 2> /dev/null
cp ./*.png ../../../output/share/urusstudio/images/settings/ > /dev/null 2> /dev/null
exit 0


