#!/bin/bash
mkdir -p ../../../output
zip -j9 ../../../devel/share/urusstudio/codesnippets.zip ./manifest.xml
mkdir -p  ../../../devel/share/urusstudio/images/codesnippets > /dev/null 2> /dev/null
mkdir -p ../../../output/share/urusstudio/images/codesnippets > /dev/null 2> /dev/null
cp ./resources/*.png ../../../devel/share/urusstudio/images/codesnippets/ > /dev/null 2> /dev/null
cp ./resources/*.png ../../../output/share/urusstudio/images/codesnippets/ > /dev/null 2> /dev/null
exit 0
